
# standard alphabet
LETTERS_IN_ALPHABET = 26
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"


# rotor wiring configurations
ROTOR_I_WIRING = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
ROTOR_II_WIRING = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
ROTOR_III_WIRING = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
ROTOR_IV_WIRING = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
ROTOR_V_WIRING = "VZBRGITYUPSDNHLXAWMJQOFECK"

# rotor turnover notch positions
ROTOR_I_NOTCH_POSITION = "Q"
ROTOR_II_NOTCH_POSITION = "E"
ROTOR_III_NOTCH_POSITION = "V"
ROTOR_IV_NOTCH_POSITION = "J"
ROTOR_V_NOTCH_POSITION = "Z"

# reflector wiring configurations
REFLECTOR_A_WIRING = "EJMZALYXVBWFCRQUONTSPIKHGD"
REFLECTOR_B_WIRING = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
REFLECTOR_C_WIRING = "FVPJIAOYEDRZXWGCTKUQSBNMHL"


# pygame
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
TEXT_MARGIN = {"top": 200, "bottom": 100, "left": 100, "right": 100}
COMPONENT_SPACING = 100


# number of enigma components
ENIGMA_COMPONENTS = 6  # 7
COMPONENT_NAMES = ["Reflector", "Left", "Middle", "Right", "Plugboard", "Keyboard"]


# signal display
INPUT = ""
OUTPUT = ""
PATH = []
SIGNAL_COORDINATES = 20
